spring:
  application:
    name: "helloworlddb"

  # Database Configuration (from container-compose.yml)
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 300000
      max-lifetime: 1200000
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: HikariPoolHelloWorld
      initialization-fail-timeout: -1   # don’t fail fast if DB not ready yet

  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: helloworld
        jdbc:
          time_zone: UTC
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: ${spring.jpa.properties.hibernate.dialect}

  # Flyway Configuration
    # flyway:
    # enabled: true
    # baseline-on-migrate: true
    # locations: classpath:db/migration
    # schemas: ${spring.jpa.properties.hibernate.default_schema}
    # default-schema: ${spring.jpa.properties.hibernate.default_schema}

management:
  endpoints:
    web:
      exposure:
        include: health, info
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState
        liveness:
          include: livenessState